markdown: rdiscount
permalink: /:categories/:title.html
rdiscount:
    extensions: [smart]

gems:
  - jekyll-sitemap

highlighter: rouge
name: Max Brenner
url: https://brennerm.github.io
description: A blog you may like.
twitter: __brennerm
