markdown: kramdown
permalink: /:categories/:title.html
highlighter: rouge
name: Max Brenner
url: https://brennerm.github.io
description: The blog of brennerm sharing his discoveries every now and then. Currently writing about DevOps related stuff, like Kubernetes, GitOps and Service Meshes.
twitter: __brennerm
