markdown: rdiscount
permalink: /:categories/:title.html
rdiscount:
    extensions: [smart]

gems:
  - jekyll-sitemap

highlighter: pygments
name: Max Brenner
url: http://brennerm.github.io
description: A blog you may like.
twitter: __brennerm
